version: '3.8'
services:
  app:
    build: .
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
    volumes:
      - ./src:/usr/src/app
      
    command: bash -c "cp .env.example .env && npm i && npx ts-node-dev --clear --poll app.ts" #remplacer par "npm i && npx ts-node app.ts" en prod (node-dev utilise du CPU)
